In [1]:
# 1. Create Numpy Arrays:  total 28 points

import numpy as np
np.__version__

'1.17.2'

In [4]:
# 1) Create an array of [1, 2, 3].    - 1 point

x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [5]:
# 2) Let x = [1, 2]. Convert it into an array.  - 1 point

x = [1, 2]
res = np.asarray(x)
res

array([1, 2])

In [6]:
# 3) Create a new array of 3 x 2 float numbers, filled with ones.  - 1 point

x = np.ones([3, 2], dtype = float)
x

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
# 4) Create a 3-D array with ones on the diagonal and zeros elsewhere.  - 1 point

x = np.zeros([5, 5, 5], dtype=int)
a = np.arange(5)
x[a, a, a] = 1
x

array([[[1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 1]]])

In [13]:
# 5) Create a new array of 2 x 5 uints, filled with 6.   - 2 point

x = np.full([2, 5], 6)
x

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [14]:
# 6) Create an array of 2, 4, 6, 8, ..., 98, 100.   - 2 point

x = np.arange(2, 101)[::2]
x

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [16]:
# 7) create an array of 10 zeros; another array of 10 fives. - 2 points

a = np.zeros(10, dtype=int)
print(a)
b = np.full([10], 5)
print(b)

[0 0 0 0 0 0 0 0 0 0]
[5 5 5 5 5 5 5 5 5 5]


In [17]:
# 8) create a 3x3x3 array filled with arbitrary values. - 2 points

x = np.random.randint(1000, size=[3, 3, 3])
x

array([[[844, 754, 564],
        [ 37, 513, 422],
        [483, 355, 244]],

       [[933, 155, 569],
        [749, 152,  75],
        [863,  67, 890]],

       [[436, 317,  52],
        [944, 573, 369],
        [219, 555, 858]]])

In [18]:
# 9) create a 3x4 matrix filled with values from 10 to 21 (inclusive). - 6 ponits

x = np.arange(10, 22).reshape([3, 4])
x

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [11]:
# 10) Create an 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal. Please use the numpy "slicing" method to realize.
#      - 10 points
# If students use other methods to get the same result, TA only can give 4 points.

x = np.zeros((4, 4), dtype=int)
x[::2, 1::2] = 1
x[1::2, ::2] = 1
print(x)

[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]


In [12]:
# 2. Numpy Randm Number  - total 8 points
# 1) Assign number 10 to the seed of the random generator so that you can get the same value next time.   - 2 point
# 2) Create an array of shape (3, 2) and populate it with random samples from a uniform distribution over [0, 1).  - 2 point
# 3) Create an array of shape (3, 2) and populate it with random integers ranging from 0 to 3 (inclusive) from a discrete uniform distribution. 
#     - 4 points

np.random.seed(10)
print(np.random.rand(3, 2))
print(np.random.randint(0, 4, size = (3, 2)))

[[0.77132064 0.02075195]
 [0.63364823 0.74880388]
 [0.49850701 0.22479665]]
[[1 2]
 [0 1]
 [0 2]]


In [13]:

# 3. Operate on Numpy Arrays: total 23 points


In [14]:
# 1) Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order. - 4 points

x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
x1, x2, x3 = np.split(x, [4, 6])
print(x1, x2, x3)

[1 2 3 4] [5 6] [7 8 9]


In [15]:
# 2) Given an array    - 8 points
# [[ 0., 1., 2., 3.],
# [ 4., 5., 6., 7.],
# [ 8., 9., 10., 11.],
# [ 12., 13., 14., 15.]].
# Split it into two arrays along the second axis.

arr = np.array([[ 0., 1., 2., 3.],
                [ 4., 5., 6., 7.],
                [ 8., 9., 10., 11.],
                [ 12., 13., 14., 15.]])
arr1, arr2 = np.split(arr, 2, axis=1)
print(arr1)
print(arr2)

[[ 0.  1.]
 [ 4.  5.]
 [ 8.  9.]
 [12. 13.]]
[[ 2.  3.]
 [ 6.  7.]
 [10. 11.]
 [14. 15.]]


In [16]:
# 3) Given an array: [[5,10,15],[20,25,30],[35,40,45]]   - 4 points
# (1) Slicing to get the sub-array [[10,15],[25,30]]
# (2) Getting individual element value "20"

x = np.array([[5,10,15],[20,25,30],[35,40,45]])
print(x[:2, 1:])
print(x[1, 0])

[[10 15]
 [25 30]]
20


In [17]:
# 4)  - 6 points
# Let x be an array
# [[ 1 2 3]
#  [ 4 5 6]].

# and y be an array
# [[ 7 8 9]
#  [10 11 12]].

# Concatenate x and y so that a new array looks like
# [[1, 2, 3, 7, 8, 9],
#  [4, 5, 6, 10, 11, 12]].

x = np.array([[1, 2, 3],
             [4, 5, 6]])
y = np.array([[7, 8, 9],
             [10, 11, 12]])
print(np.concatenate([x, y], axis = 1))

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [18]:

# 4. Array Slicing: total 10 points, 2 points each
# Given an array: 
# array([ 3,  6,  9,  25, 10,  8])

x = np.array([3, 6, 9, 25, 10, 8])

In [19]:
# 1) To get all elements except the first:

x[1:]

array([ 6,  9, 25, 10,  8])

In [20]:
# 2) To get all elements except the last:

x[:5]

array([ 3,  6,  9, 25, 10])

In [21]:
# 3) To get every other element of the array (operation from the first element):

x[::2]

array([ 3,  9, 10])

In [22]:
# 4) To get every element of the array (operation from the second element):

x[1::2]

array([ 6, 25,  8])

In [23]:
# 5) To reverse the array:

x[::-1]

array([ 8, 10, 25,  9,  6,  3])

In [24]:

# 5. Multidimensional Arrays: total 4 points, 1 points each


In [25]:
# 1) create an array with the components as 0-31 and the shape is (8,4)

x = np.arange(0, 32).reshape(8, 4)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [26]:
# 2) set the 3rd element in the 1st row to 0

x[0, 2] = 0
print(x)

[[ 0  1  0  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [27]:
# 3)  the second column

x[:, 1]

array([ 1,  5,  9, 13, 17, 21, 25, 29])

In [28]:
# 4) select any 3x3 region from the array

x[2:5, 0:3]

array([[ 8,  9, 10],
       [12, 13, 14],
       [16, 17, 18]])

In [20]:

# 6. Create a random array with 1000 elements and compute the average, variance, standard deviation of the array elements.   - 7 points
# And print the formatted outputs which keep 5 digits after the decimal point.

L = np.random.random(1000)
mea = np.mean(L)
var = np.var(L)
std = np.std(L)
print("Average: {:,.5f}" .format(mea))
print("Variance: {:,.5f}" .format(var))
print("Standard deviation: {:,.5f}" .format(std))

Average: 0.49854
Variance: 0.08244
Standard deviation: 0.28713


In [30]:
# 1) 
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])

b = np.reshape(b, [3, 1])
a + b

array([[ 1., 11., 21., 31.],
       [ 2., 12., 22., 32.],
       [ 3., 13., 23., 33.]])

In [35]:
# 2) 
x = np.arange(4)
y = np.ones(5)

x[:, np.newaxis] + y

array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

In [ ]:

# 8. Write a 6x6 times table matrix:  total 10 points 
#     - by using numpy broadcasting (5 points) 
#     - by using Python nested for-loop (5 points).
    

In [22]:
x1 = np.arange(1, 7)
x2 = np.arange(1, 7).reshape(6, 1)
res = x1 * x2;
print(res)

[[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]
 [ 4  8 12 16 20 24]
 [ 5 10 15 20 25 30]
 [ 6 12 18 24 30 36]]


In [24]:
x = np.arange(1, 7)
res = np.zeros((6, 6), dtype = int)
for a in x:
    for b in x:
        res[a - 1][b - 1] = a * b
print(res)

[[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]
 [ 4  8 12 16 20 24]
 [ 5 10 15 20 25 30]
 [ 6 12 18 24 30 36]]
